//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ASSAR.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_DIALOG_PPI_PLOT             103
#define IDS_PROPSHT_CAPTION             104
#define IDD_PROPPAGE1                   105
#define IDD_PROP_RADAR_IDENTITY         105
#define IDD_PROPPAGE2                   106
#define IDD_PROP_RADAR_TX               106
#define IDD_PROPPAGE3                   107
#define IDD_PROP_RADAR_RXSIGNALPROCESSING 107
#define IDD_PROPPAGE4                   108
#define IDD_PROP_RADAR_ANTENNA          108
#define IDD_PROPPAGE5                   109
#define IDD_PROP_RADAR_INDICATOR        109
#define IDS_PROPSHT_CAPTION1            110
#define IDD_PROP_JAMMER_IDENTITY        111
#define IDD_PROP_JAMMER_RXTX            112
#define IDD_PROP_JAMMER_ANTENNA         113
#define IDD_PROPPAGE41                  114
#define IDD_PROP_JAMMER_JAMODE1         114
#define IDD_PROPPAGE51                  115
#define IDD_PROP_JAMMER_JAMODE2         115
#define IDS_PROPSHT_CAPTION2            116
#define IDD_PROP_TARGET_IDENTITY        117
#define IDD_PROPPAGE22                  118
#define IDD_PROP_SYMBOL                 118
#define IDB_SPLASH2                     119
#define ID_INDICATOR_SIMTIME            120
#define IDR_MAINFRAME                   128
#define IDR_RADARPTYPE                  129
#define IDB_BITMAP1                     137
#define IDB_BITMAP2                     138
#define IDR_MENU_RADAR                  139
#define IDB_BITMAP3                     142
#define IDR_MENU_JAMMER                 143
#define IDR_MENU_TARGET                 144
#define IDR_MENU_RUN                    148
#define IDD_DIALOGOVERVIEW              157
#define IDD_PROP_RADAR_ECCM             160
#define IDD_PROP_RADAR_RXSIGNALPROCESSING2 162
#define IDD_DLG_KALIBRERA               164
#define IDI_ICONSTOP                    167
#define IDB_BITMAP4                     169
#define IDB_BITMAP5                     170
#define IDB_BITMAP6                     171
#define IDB_BITMAP_JAS2                 173
#define IDB_BITMAP_VISBY                174
#define IDB_BITMAP_RADARPPI             177
#define IDB_SPLASH                      178
#define IDI_ICON_TEST                   181
#define IDI_ICON_JAMNAME                182
#define IDI_ICON_PLAY                   183
#define IDI_ICON_PAUS                   184
#define IDB_BIT_MOVE                    186
#define IDD_DIALOG_CHOISE               187
#define IDI_ICON_WARNING                188
#define IDD_DIALOG_DIAGRAM              189
#define IDD_DIALOG_RADARPPI             190
#define IDB_BITMAP_MONA                 191
#define IDB_BITMAP_JONNE                192
#define IDB_BITMAP_RUNNER               193
#define IDD_DIALOG1                     196
#define IDD_DIALOG_RANDOM               200
#define IDR_MENU_VIEW_RUN               207
#define IDB_BITMAP_L39                  210
#define IDB_BITMAP_L_39                 211
#define IDB_BITMAP_L39299X160           212
#define IDD_DIALOG_CHART                222
#define IDC_LOKALTIME_STATIC            1005
#define IDC_EDIT_NAME                   1006
#define IDC_EDIT_JAMMERNAME             1007
#define IDC_EDIT_DISTANCETORADAR        1013
#define IDC_EDIT_BEARING                1014
#define IDC_EDIT_VELOCITY               1015
#define IDC_EDIT_TARGETNAME             1016
#define IDC_EDIT_COURSE                 1017
#define IDC_COMBO_ANTENNATYPE           1020
#define IDC_EDIT_WIDTHMAINLOBE          1021
#define IDC_EDIT_GAINMAINLOBE           1022
#define IDC_EDIT_SIGMA                  1022
#define IDC_EDIT_SUPRESSIONSPILLOVERLOBE 1023
#define IDC_EDIT_PEAKPOWER              1023
#define IDC_EDIT_GAINSPILLOVERLOBE      1023
#define IDC_EDIT_SPILLOVERLOBESUPRESSION 1023
#define IDC_EDIT_WIDTHSPILLOVERLOBE     1024
#define IDC_EDIT_PULSEWIDTH             1024
#define IDC_EDIT_OFFSETSPILLOVERLOBE    1025
#define IDC_CHECK_FIXFREQ               1025
#define IDC_EDIT_SUPRESSIONBACKLOBE     1026
#define IDC_CHECK_PULSEGROUP            1026
#define IDC_EDIT_GAINBACKLOBE           1026
#define IDC_EDIT_BACKLOBESUPRESSION     1026
#define IDC_EDIT_WIDTHBACKLOBE          1027
#define IDC_EDIT_NBROFPULSES            1027
#define IDC_EDIT_CHANNELSEPARATION      1028
#define IDC_EDIT_WIDTHMAINLOBE2         1028
#define IDC_EDIT_MINFREQ                1029
#define IDC_EDIT_GAINMAINLOBE2          1029
#define IDC_EDIT_MAXFREQ                1030
#define IDC_EDIT_SPILLOVERLOBESUPRESSION2 1030
#define IDC_COMBO_PRITYPE               1031
#define IDC_EDIT_WIDTHSPILLOVERLOBE2    1031
#define IDC_EDIT_PRI                    1032
#define IDC_EDIT_OFFSETSPILLOVERLOBE2   1032
#define IDC_EDIT_PRIDEVIATION           1033
#define IDC_EDIT_BACKLOBESUPRESSION2    1033
#define IDC_EDIT_WIDTHBACKLOBE2         1034
#define IDC_EDIT6                       1038
#define IDC_EDIT_TIMELINE               1038
#define IDC_EDIT7                       1039
#define IDC_EDIT_JAM3                   1039
#define IDC_EDIT_RAD3                   1040
#define IDC_EDIT9                       1041
#define IDC_EDIT10                      1042
#define IDC_EDIT_PULSECOMPRATIO         1042
#define IDC_CHECK1                      1044
#define IDC_EDIT11                      1045
#define IDC_CHECK3                      1045
#define IDC_EDIT_SNRMIN                 1045
#define IDC_CHECK2                      1046
#define IDC_CHECK4                      1046
#define IDC_EDIT12                      1047
#define IDC_CHECK5                      1047
#define IDC_EDIT13                      1048
#define IDC_CHECK6                      1048
#define IDC_EDIT14                      1049
#define IDC_CHECK7                      1049
#define IDC_COMBO1                      1050
#define IDC_CHECK8                      1050
#define IDC_COMBO_INDICATORTYPE         1050
#define IDC_EDIT1                       1051
#define IDC_COMBO2                      1052
#define IDC_COMBO_MODE                  1052
#define IDC_EDIT2                       1053
#define IDC_EDIT3                       1054
#define IDC_EDIT4                       1055
#define IDC_EDIT_BANDWIDTH_BARRAGE      1055
#define IDC_EDIT_JAM6                   1055
#define IDC_EDIT5                       1056
#define IDC_EDIT_RAD6                   1056
#define IDC_EDIT_SENSITIVITY            1057
#define IDC_EDIT_RAD7                   1057
#define IDC_CHECK_DEFLECTION            1058
#define IDC_EDIT_RAD8                   1058
#define IDC_EDIT_SIGMAREF               1059
#define IDC_EDIT_JAM4                   1059
#define IDC_EDIT_RAD4                   1060
#define IDC_EDIT_SIGMAREF2              1060
#define IDC_EDIT_MAXRANGE               1061
#define IDC_COMBO_COLOR                 1062
#define IDC_STATIC_TIME                 1063
#define IDC_STATIC_NOISE                1064
#define IDC_COMBO_JAMMODE               1065
#define IDC_COMBO3                      1066
#define IDC_COMBO_SYNC                  1066
#define IDC_EDIT_ANTENNAGAINTX          1067
#define IDC_EDIT_BEAMWIDTHTX            1068
#define IDC_EDIT_FREQMAX                1069
#define IDC_EDIT_FREQMIN                1070
#define IDC_EDIT_ANTENNAGAINRX          1071
#define IDC_EDIT_FREQMIN2               1071
#define IDC_EDIT_BEAMWIDTHRX            1072
#define IDC_EDIT_FREQMAX2               1072
#define IDC_BUTTON_CALCMAXRANGE         1079
#define IDC_SPIN_LOSSES                 1085
#define IDC_SPIN_PROCESSINGGAIN         1086
#define IDC_EDIT_LOSSES                 1089
#define IDC_EDIT_PROCESSINGGAIN         1090
#define IDC_SPIN_ANTENNAGAIN            1091
#define IDC_SPIN_PEAKPOWER              1092
#define IDC_EDIT_ANTENNAGAIN            1093
#define IDC_EDIT_VELOCITY_KMH           1094
#define IDC_EDIT_ANTENNAGAIN2           1094
#define IDC_EDIT_VELOCITY_KNOP          1095
#define IDC_SPIN_ANTENNAGAIN2           1095
#define IDC_EDIT_PRF                    1096
#define IDC_EDIT_PULSEGROUPNBROFPULSES  1098
#define IDC_EDIT_REPEATERDELAY          1099
#define IDC_EDIT_APPLIEDDOPPLER         1100
#define IDC_EDIT_DUTYCYCLE              1101
#define IDC_EDIT_DISTANCEBETWEEN        1102
#define IDC_EDIT_TIMEBETWEEN            1103
#define IDC_COMBO_PATTERN               1104
#define IDC_EDIT_REPEATED_PULSEWIDTH    1105
#define IDC_EDIT_CLOCKRATE              1113
#define IDC_EDIT_SIDELOBESUPRESSION     1114
#define IDC_EDIT_IFBANDWIDTH            1115
#define IDC_EDIT_SIDELOBESUPRESSION2    1115
#define IDC_EDIT_SCANPERIOD             1115
#define IDC_EDIT_JSRATIO                1116
#define IDC_CHECK_COHERENTINTEGRATION   1117
#define IDC_EDIT_SIDELOBESUPRESSION3    1117
#define IDC_COMBO_POLARIZATION          1118
#define IDC_EDIT_IFBANDWIDTH2           1118
#define IDC_EDIT_JSRATIO2               1119
#define IDC_EDIT_PROPABILITY            1119
#define IDC_EDIT_NOISEFIGURE            1119
#define IDC_COMBO_TYPE                  1120
#define IDC_EDIT_PROPABILITY2           1121
#define IDC_EDIT_RADARFREQFORDOPPLER    1122
#define IDC_EDIT_LOWERVELOCITYLIMIT     1123
#define IDC_EDIT_ATTENUATION            1124
#define IDC_CHECK_MTI                   1125
#define IDC_EDIT_CENTERFREQ             1127
#define IDC_EDIT_SETONDELAY             1128
#define IDC_EDIT_BANDWIDTH_TRACKING     1129
#define IDC_CUSTOM1                     1133
#define IDC_BUTTON1                     1135
#define IDC_BUTTON_JAMMODE1             1136
#define IDC_BUTTON_JAMMODE2             1137
#define IDC_BUTTON_JAMMODE3             1138
#define IDC_BUT_FFW                     1139
#define IDC_TIMELINE                    1140
#define IDC_BUTTON_JAMMODE4             1142
#define IDC_BUTTON_OFF                  1154
#define IDC_EDIT_JAM5                   1156
#define IDC_EDIT_JAM1                   1157
#define IDC_EDIT_JAM2                   1158
#define IDC_BUTTON_RESTORE              1159
#define IDC_STATIC_FRAME                1160
#define IDC_EDIT_RAD1                   1161
#define IDC_EDIT_RAD2                   1162
#define IDC_EDIT_RAD5                   1163
#define IDC_BUT_WAYPOINT                1165
#define IDC_BUT_MOVE                    1166
#define IDC_BUT_DELETEWAYPOINT          1167
#define IDC_STATIC_CHOISE               1168
#define IDC_BUTTON_RADSYNTETIC          1169
#define IDC_BUTTON_RADRAWVIDEO          1170
#define IDC_BUT_REW                     1171
#define IDC_BUTTON_PAUS                 1172
#define IDC_BUT_SHOWDISK                1173
#define IDC_STATIC_COOR                 1174
#define IDC_STATIC_DISTTORADAR          1175
#define IDC_STATIC_PREVIEW              1176
#define IDC_CHECK_ALLWAYPOINTS          1181
#define IDC_BUT_DEGREES                 1182
#define IDC_LOOKUP_BUTTON               1183
#define IDC_CHECK_INVERSEGAIN           1184
#define IDC_CHECK_CONSTANTPOWER         1185
#define IDC_CHECK_INVERSEGAIN2          1185
#define IDC_CHECK_CONSTANTGAIN          1186
#define IDC_CHECK_CONSTANTPOWER2        1186
#define IDC_EDIT_DYNAMICRANGE           1187
#define IDC_CHECK_CONSTANTGAIN2         1187
#define IDC_EDIT_LOOPGAIN               1188
#define IDC_EDIT_DYNAMICRANGE2          1189
#define IDC_SPIN1                       1191
#define IDC_CHECK_FROMFILE              1196
#define IDC_STATIC_FILENAME             1197
#define IDC_PPIPLOT_STATIC              1354
#define ID_BUTTON_PPI                   32771
#define ID_BUTTON_UTR                   32773
#define ID_BUTTON_CLR                   32774
#define ID_BUTTON_BRUS                  32775
#define ID_BUTTON_SVEPHASTIGHET         32776
#define ID_SETTINGS_GENERAL             32777
#define ID_SETTINGS_RADAR               32778
#define ID_BUTTON_CREATE_RADAR          32784
#define ID_BUTTON_CREATE_JAMMER         32785
#define ID_BUTTON_CREATE_TARGET         32786
#define ID_BUTTON_CLEARALL              32787
#define ID_DELETE_RADAR                 32788
#define ID_PROPERTIES_JAMMER            32789
#define ID_DELETE_JAMMER                32790
#define ID_PROPERTIES_TARGET            32791
#define ID_DELETE_TARGET                32792
#define ID_PROPERTIES_RADAR             32793
#define ID_MENU_STOP                    32795
#define ID_MENU_RUN                     32796
#define ID_VIEW_SENARIO                 32797
#define ID_MENU_PAUSE                   32798
#define ID_MENUD_ZOOMIN                 32799
#define ID_MENUD_ZOOMOUT                32800
#define ID_MENUD_FITTOSCREEN            32801
#define ID_MENUD_RAWVIDEOMODE           32802
#define ID_MENUD_SYNTETICMODE           32803
#define ID_MENUD_RAWVIDEOSYNTETIC       32804
#define ID_VIEW_OVERVIEW                32805
#define ID_OPENRADAR                    32806
#define ID_SAVERADAR                    32807
#define ID_OPENJAMMER                   32808
#define ID_SAVEJAMMER                   32809
#define ID_KALIBRERA_RADAR              32810
#define ID_BUTTON_STOP                  32811
#define ID_BUTTON32816                  32816
#define ID_BUTTON32817                  32817
#define ID_BUTTON32818                  32818
#define ID_MENU_FASTER                  32819
#define ID_MENU_SLOWER                  32820
#define ID_DIAGRAMS_EFFECT              32821
#define ID_SHOW_PPI                     32822
#define ID_ANALASYS_FILMCLIP            32823
#define ID_VIEW_EXTRA                   32824
#define ID_FILE_IMPORT                  32827
#define ID_FILE_EXPORT                  32828
#define ID_FILE_SAVEAS                  32830
#define ID_FILE_SAVEALL                 32832
#define ID_SIMULATION_START             32834
#define ID_SIMULATION_STOP              32835
#define ID_SCENARIO_ADDRADAR            32836
#define ID_SCENARIO_ADDJAMMER           32837
#define ID_SCENARIO_ADDTARGET           32838
#define ID_SCENARIO_CLEAR               32839
#define ID_SIMULATION_PREFERENCES       32840
#define ID_SIMULATION_FULLSCREEN        32841
#define ID_R_JAMMODE1                   32842
#define ID_R_JAMMODE2                   32843
#define ID_R_FULLSCEEN                  32844
#define ID_R_JAMMEROFF                  32845
#define ID_R_STOP                       32846
#define ID_R_PAUSE                      32847
#define ID_R_RESUME                     32848
#define ID_SIMULATION_PAUSE             32849
#define ID_SIMULATION_RESUME            32850
#define ID_A_ANTENNADIAGRAM             32851
#define ID_ANTENNACHART                 32852

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        223
#define _APS_NEXT_COMMAND_VALUE         32853
#define _APS_NEXT_CONTROL_VALUE         1201
#define _APS_NEXT_SYMED_VALUE           121
#endif
#endif
